[bloomery]
mold = "c++"

[meta]
name = "C++"
version = "0.1"
author = "k6303"
description = "Default C++ compilation mold"

[definitions]
compiler = "g++"
standard = "17"
flags = "-std=c++{mold.standard}"
files = { ending = [".cpp", ".cc", ".cxx", ".c"] }
ext = { on = "platform", windows = ".exe", default = "" }
output = "-o {input}{mold.ext}"

[tasks.build]
command = "{mold.compiler}"
flags = "{mold.flags}"
files = { ending = [".cpp", ".cc", ".cxx", ".c"] }
output = "{mold.output}"

[tasks.run]
depends = ["build"]
always_run = true
command = "{task.build.outputs}"
